10 raycast cleanup
JadenCooper/BogBuddiesToilets pull request #199
Opened 2023-09-11 16:45 UTC by SB-Lamia

I did some testing and experimented with a few things and decided that the best way to do the raycast would be using raycastall.

Basically it makes it so the raycast goes through as many objects as it wants (with a max distance it can go) and wont get blocked anymore. then it will check each object it interacted with and see if its an arrow or info bit. and then interact with it 

after that it breaks out and ends the foreach loop. I have tested it abit (via force moving the player around) and it seems to fix all the previous problems. New Script looks like this:

```
Ray ray = Camera.main.ScreenPointToRay(Look.action.ReadValue<Vector2>());
                RaycastHit[] hits = Physics.RaycastAll(ray, 200f);
                foreach (RaycastHit hitinfo in hits)
                {
                    if (hitinfo.collider.CompareTag("Information")) // Text Tag Is For Intractable Doesn't Work On Any Other Tag For Some Reason
                    {
                        hitinfo.collider.GetComponent<Interactable>().Interact(); // Activates Object's Interaction
                        break;
                    }
                    if (hitinfo.collider.CompareTag("Arrow")) // Text Tag Is For Intractable Doesn't Work On Any Other Tag For Some Reason
                    {
                        hitinfo.collider.GetComponent<Interactable>().Interact(); // Activates Object's Interaction
                        break;
                    }
                }
```

2023-09-13 09:58 UTC, JadenCooper requested changes
I'm able to interact with the interactables through walls 
![image](https://github.com/JadenCooper/BogBuddiesToilets/assets/83618082/cc01e4c0-a00a-4a7d-9e48-6dcf6469f0b8)
From here I was pressing and I opening/closing doors and setting off toilets. Is there maybe a way to add a distance check or somthing?

2023-09-14 01:08 UTC, SB-Lamia commented
> I'm able to interact with the interactables through walls ![image](https://user-images.githubusercontent.com/83618082/267613672-cc01e4c0-a00a-4a7d-9e48-6dcf6469f0b8.png) From here I was pressing and I opening/closing doors and setting off toilets. Is there maybe a way to add a distance check or somthing?

yes, I can set it to much closer. its just a value change in the code.

2023-09-14 01:28 UTC, SB-Lamia commented
> I'm able to interact with the interactables through walls ![image](https://user-images.githubusercontent.com/83618082/267613672-cc01e4c0-a00a-4a7d-9e48-6dcf6469f0b8.png) From here I was pressing and I opening/closing doors and setting off toilets. Is there maybe a way to add a distance check or somthing?

raycast is not set to 3, instead of 200 for the distance. this is the min I could find that would still reach the toilets in some areas. it might still go through walls. but that is the risk / reward of using raycastall instead of normal raycast.

2023-09-14 01:29 UTC, JadenCooper approved these changes

2023-09-14 01:59 UTC, merged